### ISSUE TITLE
Multiple comparisons

### ISSUE THREAD

**Issue by pushline** [oscar-broman/samp-inline-sort#4]
Hello, i don't think you'll see this soon, but i have a question. Does sort-inline is capable of multiple comparisons? Example below.

```
R = (playerid[l][money] > playerid[r][money] && playerid[l][cash] > playerid[r][cash])
```

Example dummy code, not my real code.

**Comment by oscar-broman** [comment]
Yes, that will work just fine

**Comment by pushline** [comment]
Thanks
